# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "Hanoi" # The application time zone will be used by default if not set

# Runs once every 2 minutes
simple_task:
  class: "SeederJob"
  every: "2.minutes"

# Runs once every 5 minutes
simple_task:
  class: "Consumerob"
  every: "5.minutes"  